# app/logic/custom_py_generator.py
from pathlib import Path
from app.models import CustomPyCreate


class CustomPyGenerator:
    """Генератор файла custom.py для сборки движка Godot."""

    @staticmethod
    def generate(folder: str, params: dict, filename: str = "custom.py") -> dict:
        """
        Генерирует файл custom.py.

        Args:
            folder: путь к папке для сохранения
            params: словарь {имя_параметра: значение}
            filename: имя файла (по умолчанию custom.py)

        Returns:
            dict: {"ok": bool, "message": str, "message_extra": str}
        """
        folder_path = Path(folder)
        if not folder_path.is_dir():
            return {"ok": False, "message": "api_folder_not_exist"}

        # Нормализация имени файла
        filename = Path(filename).name or "custom.py"
        if not filename.endswith(".py"):
            filename += ".py"

        lines = ["# Generated by Godot PCK Compressor", ""]
        for name, value in params.items():
            lines.append(f'{name}="{value}"')
        lines.append("")

        try:
            target = folder_path / filename
            with open(target, "w", encoding="utf-8") as f:
                f.write("\n".join(lines))
            return {"ok": True, "message": "build_generated_ok", "message_extra": str(target)}
        except Exception as e:
            return {"ok": False, "message": "build_generated_failed", "message_extra": str(e)}

    @staticmethod
    def list_py_files(folder: str) -> dict:
        """
        Возвращает список .py файлов в папке.

        Args:
            folder: путь к папке

        Returns:
            dict: {"ok": bool, "message": str, "files": list}
        """
        folder_path = Path(folder)
        if not folder_path.is_dir():
            return {"ok": False, "message": "api_folder_not_exist", "files": []}

        try:
            files = sorted(
                entry.name for entry in folder_path.iterdir()
                if entry.is_file() and entry.suffix == ".py"
            )
            return {"ok": True, "message": "api_files_ok", "files": files}
        except Exception as e:
            return {"ok": False, "message": "api_error", "message_extra": str(e), "files": []}

    @staticmethod
    def get_custompy_file(folder: str, file: str) -> CustomPyCreate:
        """
        Возвращает содержимое указанного .py файла в виде модели CustomPyCreate.

        Args:
            folder: путь к папке
            file: имя файла

        Returns:
            CustomPyCreate: модель с полями filename и content (предполагаемая структура)
        """
        folder_path = Path(folder)
        file_path = folder_path / file
        custom_py = CustomPyCreate(filename=file, folder=folder)

        if not file_path.is_file() or file_path.suffix != ".py":
            return custom_py

        try:
           with open(file_path, "r") as f:
                for line in f.readlines():
                    if "=" in line:
                        parts = line.split("=")
                        
                        if len(parts) == 2:
                            parts = [p.strip().strip('"') for p in parts]
                            custom_py.params[parts[0]] = parts[1]
               
        except Exception as e:
            print(e)

        return custom_py